### ISSUE TITLE
No rule to make target 'tcb-convert'

### ISSUE THREAD

**Issue by duytongdev** [root670/ddr-tools#1]
First of all, thanks for sharing this tool.
In directory:
`C:\ddr-tools\build`
I couldn't run successfully with this cmd:
`make ./tcb-convert e ./0004.tcb`
or
`make -f  ./tcb-convert e ./0004.tcb`
What's wrong with above cmd? Where I was wrong?
And Is this file a TCB?
http://www.mediafire.com/file/nx1ayqgndfv3oso/0004.tcb/file
I got this "ERROR: Invalid TCB file"

**Comment by root670** [comment]
You have to run `make` first, then once compilation has finished you can run the executables.

As for the TCB file in the link, it looks like it's from a compressed file but it's missing the initial flag byte. You'll need to use `tcb-extract 1 <path>` to attempt to extract TCB files from the file this came from. If the linked file was created by `tcb-extract`, then there's a bug.
