### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jch02140** [root670/ddr-tools#2]
Hi,

I tried compiling the extracted folder of the ddr tools with cmake-gui but got the following error:

"Error in configuration process, project file may be invalid."

How should I proceed?

Best Regards,

**Comment by root670** [comment]
Can you try running `cmake` from the terminal using the build instructions in the readme? That will produce a full log to help troubleshoot the issue.

Which operating system are you using?

**Comment by jch02140** [comment]
I am using Windows 10 Home Edition.

I tried putting all extracted files in the same directory as the CMake and ran the command. It gives the following error:

> CMake Error: The source directory "C:/Program Files/CMake" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.

But the CMakeLists.txt is in the same directory as the CMake... Not sure if I misinterpreted something...

**Comment by root670** [comment]
You shouldn't need to extract the files into the CMake install directory. When you install CMake it will ask if you want to add it to the system path
![](https://tulip.labri.fr/TulipDrupal/sites/default/files/uploadedFiles/users/6/screenshot_cmake01.png)
Try reinstalling CMake and making sure to choose the option to include it in the system path as shown in the image above. This will allow you to run `cmake` from any folder.

Verify it added it to the system path by opening a command prompt and running `cmake` in any folder other than where CMake is installed. Once that's working, extract ddr-tools to its own directory and try running the following:
```
mkdir build
cd build
cmake ..
```

**Comment by jch02140** [comment]
Hi,

I have reinstalled the CMake with the system path option added. Now I am able to proceed slightly further but still getting error when compiling.

I have included the output from CMakeError.txt:

```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags:  

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -c 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -Aa 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -D__CLASSIC_C__ 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags:  

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -c 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -Aa 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: -D__CLASSIC_C__ 

The output was:
The system cannot find the file specified


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: cl 
Build flags: 
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
The system cannot find the file specified


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags:  

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: -c 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --c++ 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --ec++ 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags:  

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: -c 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --c++ 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --ec++ 

The output was:
The system cannot find the file specified


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: cl 
Build flags: 
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
The system cannot find the file specified


Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
```

**Comment by root670** [comment]
Forgot to mention you need to have Visual Studio installed. Install VS 2019 Community and cmake should detect it and generate a solution file when it's run. If not, you can pass `-G"Visual Studio 16 2019"` to force it to use Visual Studio if it's installed on your machine.

**Comment by jch02140** [comment]
Hi. I am able to get the `cmake ..` command to work and compile after installing VS 2019. It produces many .vcxproj files in the build folder. However, the `make` command still doesn't seem to work as it returns an error not reconizable as an internal or external command.

**Comment by root670** [comment]
Instead of running `make` you'll want to open the solution file in VS 2019 and build the solution. This should compile everything and produce an executable.

**Comment by jch02140** [comment]
I am still getting errors using the VS 2019 to build the project files.

1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Build started: Project: bemanilz, Configuration: Release x64 ------
3>------ Build started: Project: lodepng, Configuration: Release x64 ------
4>------ Build started: Project: pngquant, Configuration: Release x64 ------
2>Building Custom Rule C:/Users/Johney Choi/Desktop/ddr-tools-master/CMakeLists.txt
2>BemaniLZ.c
2>bemanilz.vcxproj -> C:\Users\Johney Choi\Desktop\ddr-tools-master\build\Release\bemanilz.lib
5>------ Build started: Project: tcb-extract, Configuration: Release x64 ------
5>Building Custom Rule C:/Users/Johney Choi/Desktop/ddr-tools-master/CMakeLists.txt
5>tcb-extract.c
3>Building Custom Rule C:/Users/Johney Choi/Desktop/ddr-tools-master/CMakeLists.txt
5>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-extract.c(5,10): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
5>Done building project "tcb-extract.vcxproj" -- FAILED.
4>Building Custom Rule C:/Users/Johney Choi/Desktop/ddr-tools-master/CMakeLists.txt
3>lodepng.c
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(801,61): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(813,46): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(831,78): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(1439,29): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(1443,31): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(1481,88): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(1515,86): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(1463,1): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(3438,54): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(3432,1): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(4240,75): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(4288,41): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(4368,59): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
3>C:\Users\Johney Choi\Desktop\ddr-tools-master\lodepng\lodepng.c(5308,1): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
4>blur.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>libimagequant.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(132,32): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(132,32): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(132,33): error C2133: 'buf': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(329,45): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(337,50): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(403,28): warning C4244: '=': conversion from 'uintptr_t' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(844,33): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(924,37): warning C4244: 'function': conversion from 'const double' to 'const float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(969,79): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(969,79): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(969,80): error C2133: 'average_color': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(992,72): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1006,66): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1008,66): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1010,66): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1021,21): warning C4305: '*=': truncation from 'double' to 'float'
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1059,72): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1060,72): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1061,72): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1062,72): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1066,114): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1069,42): warning C4305: '*=': truncation from 'double' to 'float'
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1258,55): warning C4244: '=': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1248,1): warning C4244: 'initializing': conversion from 'const float' to 'const unsigned int', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1320,48): warning C4244: '=': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1322,48): warning C4244: '=': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1387,61): warning C4244: '=': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1458,118): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1580,44): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1580,44): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1580,45): error C2133: 'rows': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1627,49): warning C4244: 'function': conversion from 'double' to 'const float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\libimagequant.c(1611,1): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
4>mediancut.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(57,1): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(215,108): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(317,28): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(317,28): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(317,29): error C2133: 'bv': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(335,52): warning C4244: 'function': conversion from 'unsigned int' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(335,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned int', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(374,1): warning C4244: 'initializing': conversion from '__int64' to 'unsigned int', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(440,111): warning C4244: '*=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\mediancut.c(506,1): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
4>mempool.c
4>nearest.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(46,1): warning C4305: 'initializing': truncation from 'double' to 'float'
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(66,38): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(66,38): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(66,39): error C2133: 'colors': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(142,32): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(142,32): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(142,33): error C2133: 'skip_index': unknown size
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\nearest.c(183,42): warning C4305: '=': truncation from 'double' to 'float'
4>pam.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.c(45,62): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.c(275,66): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>viter.c
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(120,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(121,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(122,37): warning C4244: 'function': conversion from 'const double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(130,1): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(166,50): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\pam.h(183,54): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\viter.c(58,43): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\viter.c(51,1): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\viter.c(65,79): error C2057: expected constant expression
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\viter.c(65,79): error C2466: cannot allocate an array of constant size 0
4>C:\Users\Johney Choi\Desktop\ddr-tools-master\pngquant\viter.c(65,80): error C2133: 'average_color': unknown size
4>Generating Code...
4>Done building project "pngquant.vcxproj" -- FAILED.
3>lodepng.vcxproj -> C:\Users\Johney Choi\Desktop\ddr-tools-master\build\Release\lodepng.lib
3>Done building project "lodepng.vcxproj".
6>------ Build started: Project: tcb-convert, Configuration: Release x64 ------
6>Building Custom Rule C:/Users/Johney Choi/Desktop/ddr-tools-master/CMakeLists.txt
6>tcb-convert.c
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(111,5): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(112,5): warning C4996: 'strncat': This function or variable may be unsafe. Consider using strncat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(114,15): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(151,19): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(338,26): warning C4018: '<': signed/unsigned mismatch
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(353,22): warning C4018: '<': signed/unsigned mismatch
6>C:\Users\Johney Choi\Desktop\ddr-tools-master\tcb-convert.c(298,9): warning C4101: 'len': unreferenced local variable
6>LINK : fatal error LNK1181: cannot open input file 'Release\pngquant.lib'
6>Done building project "tcb-convert.vcxproj" -- FAILED.
7>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 3 failed, 0 up-to-date, 1 skipped ==========

**Comment by root670** [comment]
Ah, it looks like I forgot to push some changes that fix compile errors on Windows. Try pulling latest and rerun cmake and it should compile successfully.

Fixes were added in #3.

**Comment by jch02140** [comment]
Thanks for the fix. 
The new version fixed the compile errors and the executables are generated.

I am able to run the command-line tools to extract and convert the TCB files.

**Comment by jch02140** [comment]
Just curious. Does the command line support wild card arguments such as tcb-convert e \*.tcb?
I tried but it literally returns error opening "\*.tcb" file.

**Comment by root670** [comment]
It doesn't support wild cards but you can achieve the same result using a batch script like this:
```
for %%f in (*.tcb) do (
  tcb-convert e %%~nf
)
```
